orange/thresh_0: 137
orange/erosion_0: 1
orange/thresh_1: 106
orange/close_1: 0
orange/open_1: 6
orange/initial_range_value: 241
orange/range_width: 36
orange/open_2: 0
orange/close_2: 20
orange/open_3: 5
orange/min_area: 1000

red/thresh_0: 207
red/thresh_1: 106
red/close_1: 6
red/open_1: 12
red/initial_range_value: 226
red/range_width: 28
red/open_2: 0
red/close_2: 7
red/open_3: 5
red/min_area: 1000

green/thresh_0: 215
green/erosion_0: 0
green/thresh_1: 106
green/close_1: 6
green/open_1: 7
green/initial_range_value: 103
green/range_width: 39
green/open_2: 3
green/close_2: 8
green/open_3: 2
green/min_area: 286

blue/thresh_0: 207
blue/thresh_1: 211
blue/close_1: 6
blue/open_1: 8
blue/initial_range_value: 152
blue/range_width: 15
blue/open_2: 0
blue/close_2: 19
blue/open_3: 6
blue/min_area: 1000

yellow/thresh_0: 76
yellow/erosion_0: 1
yellow/thresh_1: 61
yellow/close_1: 0
yellow/open_1: 6
yellow/initial_range_value: 22
yellow/range_width: 28
yellow/open_2: 3
yellow/close_2: 8
yellow/open_3: 0
yellow/min_area: 1000
