orange/thresh_0: 137
orange/thresh_1: 106
orange/close_1: 0
orange/open_1: 6
orange/initial_range_value: 241
orange/range_width: 36
orange/open_2: 0
orange/close_2: 20
orange/open_3: 5
orange/min_area: 1000

red/thresh_0: 219
red/thresh_1: 15
red/close_1: 20
red/open_1: 16
red/initial_range_value: 217
red/range_width: 35
red/open_2: 2
red/close_2: 11
red/open_3: 3
red/min_area: 1000

green/thresh_0: 215
green/thresh_1: 160
green/close_1: 7
green/open_1: 20
green/initial_range_value: 217
green/range_width: 32
green/open_2: 3
green/close_2: 9
green/open_3: 2
green/min_area: 1000

blue/thresh_0: 233
blue/thresh_1: 48
blue/close_1: 5
blue/open_1: 14
blue/initial_range_value: 148
blue/range_width: 15
blue/open_2: 0
blue/close_2: 5
blue/open_3: 0
blue/min_area: 1000

yellow/thresh_0: 76
yellow/thresh_1: 61
yellow/close_1: 0
yellow/open_1: 6
yellow/initial_range_value: 22
yellow/range_width: 28
yellow/open_2: 3
yellow/close_2: 8
yellow/open_3: 0
yellow/min_area: 1000
