area1_x: 1.539
area1_y: 1.887
area1_orientation: -1.582

area2_x: 0.891
area2_y: 1.893
area2_orientation: -1.600

area3_x: 0.282
area3_y: 2.004
area3_orientation: -1.574

area4_x: 1.561
area4_y: 1.911
area4_orientation: 1.520

area5_x: 0.940
area5_y: 1.921
area5_orientation: 1.583

area6_x: 0.346
area6_y: 2.025
area6_orientation: 1.485

casa_x: 0.307
casa_y: 0.350
casa_orientation: -1.573

deposito1_x: 0.746
deposito1_y: 0.362
deposito1_orientation: 0.005

deposito2_x: 0.654
deposito2_y: -0.336
deposito2_orientation: -0.030

deposito3_x: 0.675
deposito3_y: -0.869
deposito3_orientation: -0.233

store_deposito1_x: 0.774
store_deposito1_y: 0.440
store_deposito1_orientation: -1.591

store_deposito2_x: 0.837
store_deposito2_y: -0.344
store_deposito2_orientation: -1.580

store_deposito3_x: 0.701
store_deposito3_y: -1.130
store_deposito3_orientation: -1.546

pedido_x: 0.200
pedido_y: -0.316
pedido_orientation: -1.701
